My Application: Dweller Class Reference
Dweller Class Reference
Derives from GameObject class. Defines Dweller variables and method.
#include <Dweller.h>
Public Member Functions
Dweller (const string &kName, const int &SPECIAL_=0)
Initialize GameObject, position_, SPECIAL_, health_, radiation_, stimpak_, radaway_,outfit_ and weapon_.
virtual ~Dweller ()
destructor where will delete weapon_ and outfit_.
const int getSPECIAL ()
getter to get SPECIAL total value.
const int getCurrentHealth ()
getter to get the amount of health the dweller have.
const int getCurrentRadDamage ()
getter to get current amount of radiation the dweller have.
const int getAttackDmg ()
getter to get attack damage of dweller with or without weapon
void setPosition (const Vec2D &position_)
setter to set the position of the dweller
const Vec2D getPosition ()
getter to get the position of the dweller
void receiveHealthDamage (const int &health_)
receiver to decrease health based on the value passed in by parameter.
void receiveRadDamage (const int &radiation_)
receiver to increase radiation value and decrease health based on radiation
void receiveEquipmentDamage (const int &durability_)
receiver to decrease the durability value of outfit and weapon
void addStimpak (const int &stimpak_)
adds to the total amount of stimpak
void addRadAway (const int &radaway_)
adds the amount of radaway
void useStimpak ()
decreases amount of stimpak to increase health
void useRadAway ()
decreases number of radaway to decrease radiation
Outfit * assignOutfit (Outfit *outfit_)
assign outfit_ with new Outfit
Weapon * assignWeapon (Weapon *weapon_)
assign weapon_ with new weapon
bool isDead ()
ister to determine if the dweller is alive or not.
Public Member Functions inherited from GameObject
virtual ~GameObject ()
Decreasing the count when objects of this type is deleted.
string getName ()
Returns name of the object, getter.
Private Attributes
Vec2D position_
int SPECIAL_
int health_
int radiation_
int stimpak_
int radaway_
Outfit * outfit_
Weapon * weapon_
Additional Inherited Members
Static Public Member Functions inherited from GameObject
static int getCount ()
Returns number of object instantiated.
Protected Member Functions inherited from GameObject
GameObject (const string kName)
Initialize kName and increasing the count when objects of this type is instantiated.
Detailed Description
Derives from GameObject class. Defines Dweller variables and method.
Class Dweller:
Definition at line 25 of file Dweller.h.
Constructor & Destructor Documentation
Dweller::Dweller (const string & kName, const int & SPECIAL_ = 0)
Initialize GameObject, position_, SPECIAL_, health_, radiation_, stimpak_, radaway_,outfit_ and weapon_.
Parameters
kName - name of dweller
SPECIAL_ - dweller's SPECIAL_
Returns
void
Definition at line 14 of file Dweller.cpp.
Dweller::~Dweller () virtual
destructor where will delete weapon_ and outfit_.
Returns
void
Definition at line 29 of file Dweller.cpp.
References outfit_, and weapon_.
Member Function Documentation
void Dweller::addRadAway (const int & radaway_)
adds the amount of radaway
Parameters
radaway_ - amount of radaway to be added
Returns
void
Definition at line 224 of file Dweller.cpp.
References radaway_.
void Dweller::addStimpak (const int & stimpak_)
adds to the total amount of stimpak
Parameters
stimpak_ - amount of stimpak to be added
Returns
void
Definition at line 210 of file Dweller.cpp.
References stimpak_.
Outfit * Dweller::assignOutfit (Outfit * outfit_)
assign outfit_ with new Outfit
Parameters
outfit_ - Outfit
Returns
outfit_
Definition at line 297 of file Dweller.cpp.
References Item::getDurability(), GameObject::getName(), Outfit::getSPECIAL(), isDead(), and outfit_.
Weapon * Dweller::assignWeapon (Weapon * weapon_)
assign weapon_ with new weapon
Returns
weapon_
Definition at line 320 of file Dweller.cpp.
References Weapon::getAttackDmg(), Item::getDurability(), GameObject::getName(), isDead(), and weapon_.
const int Dweller::getAttackDmg ()
getter to get attack damage of dweller with or without weapon
Returns
total attack damage witho or without weapon
Definition at line 105 of file Dweller.cpp.
References Weapon::getAttackDmg(), Item::getDurability(), and weapon_.
const int Dweller::getCurrentHealth ()
getter to get the amount of health the dweller have.
Returns
current health of dweller
Definition at line 78 of file Dweller.cpp.
References health_.
const int Dweller::getCurrentRadDamage ()
getter to get current amount of radiation the dweller have.
Returns
current radiation value for dweller
Definition at line 91 of file Dweller.cpp.
References radiation_.
const Vec2D Dweller::getPosition ()
getter to get the position of the dweller
Returns
position of dweller
Definition at line 141 of file Dweller.cpp.
References position_.
const int Dweller::getSPECIAL ()
getter to get SPECIAL total value.
Returns
dweller's SPECIAL_ or dweller's SPECIAL added with its outfit's special value
Definition at line 44 of file Dweller.cpp.
References Item::getDurability(), Outfit::getSPECIAL(), outfit_, and SPECIAL_.
bool Dweller::isDead ()
ister to determine if the dweller is alive or not.
Returns
true/false
Definition at line 343 of file Dweller.cpp.
References health_.
Referenced by assignOutfit(), assignWeapon(), receiveHealthDamage(), receiveRadDamage(), useRadAway(), and useStimpak().
void Dweller::receiveEquipmentDamage (const int & durability_)
receiver to decrease the durability value of outfit and weapon
Parameters
durability_ - damage to durability
Returns
void
Definition at line 189 of file Dweller.cpp.
References outfit_, Weapon::receiveDamage(), Outfit::receiveDamage(), and weapon_.
void Dweller::receiveHealthDamage (const int & health_)
receiver to decrease health based on the value passed in by parameter.
Parameters
health_ - damage to health
Returns
void
Definition at line 154 of file Dweller.cpp.
References health_, and isDead().
void Dweller::receiveRadDamage (const int & radiation_)
receiver to increase radiation value and decrease health based on radiation
Parameters
radiation_ - amount of radiation received
Returns
void
Definition at line 171 of file Dweller.cpp.
References health_, isDead(), and radiation_.
void Dweller::setPosition (const Vec2D & position_)
setter to set the position of the dweller
Parameters
position_ - coordinate x and y
Returns
void
Definition at line 126 of file Dweller.cpp.
References Vec2D::x, and Vec2D::y.
void Dweller::useRadAway ()
decreases number of radaway to decrease radiation
Returns
void
Definition at line 265 of file Dweller.cpp.
References isDead(), radaway_, and radiation_.
void Dweller::useStimpak ()
decreases amount of stimpak to increase health
Returns
void
Definition at line 237 of file Dweller.cpp.
References health_, isDead(), and stimpak_.
Field Documentation
int Dweller::health_ private
Definition at line 51 of file Dweller.h.
Referenced by getCurrentHealth(), isDead(), receiveHealthDamage(), receiveRadDamage(), and useStimpak().
Outfit* Dweller::outfit_ private
Definition at line 55 of file Dweller.h.
Referenced by assignOutfit(), getSPECIAL(), receiveEquipmentDamage(), and ~Dweller().
Vec2D Dweller::position_ private
Definition at line 49 of file Dweller.h.
Referenced by getPosition().
int Dweller::radaway_ private
Definition at line 54 of file Dweller.h.
Referenced by addRadAway(), and useRadAway().
int Dweller::radiation_ private
Definition at line 52 of file Dweller.h.
Referenced by getCurrentRadDamage(), receiveRadDamage(), and useRadAway().
int Dweller::SPECIAL_ private
Definition at line 50 of file Dweller.h.
Referenced by getSPECIAL().
int Dweller::stimpak_ private
Definition at line 53 of file Dweller.h.
Referenced by addStimpak(), and useStimpak().
Weapon* Dweller::weapon_ private
Definition at line 56 of file Dweller.h.
Referenced by assignWeapon(), getAttackDmg(), receiveEquipmentDamage(), and ~Dweller().
The documentation for this class was generated from the following files:
DS_Assignment1/Dweller.h
DS_Assignment1/Dweller.cpp